### ISSUE TITLE
MiniZincIDE-2.5.2-x86_64.AppImage requires GLIBCXX_3.4.20 - CentOS7

### ISSUE THREAD

**Issue by Difladrmaus** [MiniZinc/MiniZincIDE#126] opened 2020-11-18 18:42 UTC
Appimage made it sound like it was a standalone app with required packages, but it does not work running on CentOS7.8

/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/.mount_minizih3H8a8/usr/bin/MiniZincIDE)

$ rpm -qa | grep glibc
glibc-2.17-307.el7.1.i686
glibc-common-2.17-307.el7.1.x86_64
glibc-2.17-307.el7.1.x86_64
glibc-devel-2.17-307.el7.1.x86_64
glibc-headers-2.17-307.el7.1.x86_64

$strings /usr/lib64/libstdc++.so.6 | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBC_2.3
GLIBC_2.2.5
GLIBC_2.14
GLIBC_2.4
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH

Looks like newer version of glibc is not available on CentOS7, how can I get around this issue?

**Comment by Dekker1** [comment] 2020-11-19 04:36
Hi @Difladrmaus,

Although I understand your frustrations with this problem, this is an inherent problem with packaging software for Linux. Any package format for Linux has certain limitations in relation to the distributions that can use it. AppImage reduces the limitations to not depend on any installed library, but does still have a dependency on the main `libc` implementation.

Because all mainstream linux distributions run using `glibc`, we created AppImages with this C library implementation. `glibc` is generally forward compatible, so we compile using the oldest reasonable versions we could find. In our case we decided to use Debian "oldlatest" (i.e., the oldest supported version). It seems that CentOS 7 ships an even older version of `glibc`, that would not be compatible.

Although we try to support as best as we can, we have to make a cutoff somewhere and current that is version 3.4 of `glibc`. This does not mean that MiniZinc cannot work on your machine, but merely that you will have to acquire it by some other means:

- The Snap package would likely still work as it uses an ubuntu container.
- You can compile the MiniZinc components you require yourself.

As this is not a bug, but a packaging decision I'll close this issue. Although we should likely document this limitation somewhere.

**Closed by Dekker1** 2020-11-19 04:36 UTC
