### ISSUE TITLE
Internal error: Could not determine model parameters

### ISSUE THREAD

**Issue by SebAlbert** [MiniZinc/MiniZincIDE#82] opened 2019-03-23 17:55 UTC
After failure to simply use `libminizinc` from the command line, I tried `MiniZincIDE` and realized that even this came without any configuration of my installed solvers Gecode (freshly built version 6.1.1) and Gurobi (a somewhat outdated 7.5.1) that were set in `GUROBI_HOME` and `GECODE_HOME` variables.

I went to the preferences to add a configuration and I inserted these values:
Name: Gecode
Solver ID: org.gecode
Version: 6.1.1
Executable: /usr/local/bin/fzn-gecode
Library path: /usr/local/share/gecode/mznlib
I left the checkboxes "Run with mzn2fzn" and "Run with solns2out" ticked and "Detach from IDE" unticked. Supported standard command lines are none selected (because I don't know what I am doing here).

I managed to run from the scratchbook this model:

```
output ["Hello world"]
```

although it complained a bit:

```
Compiling untitled_model.mzn
Running untitled_model.mzn
Hello world
----------
MiniZinc: internal error: not declmap.end()!=it:  solns2out_base: unexpected id in output: var_is_introduced
Solutions processor finished with non-zero exit code 1
Finished in 37msec
```

But when I try the four lines from the first steps manual:
```
var 1..3: x;
var 1..3: y;
constraint x+y > 2;
solve satisfy;
```
I get an error message in an error message window with window title `Internal error` and content `Could not determine model parameters`. I think this is weird since there are no parameters anyway, or am I wrong?

For what it's worth, I'm on Gentoo GNU/Linux with gcc 8.2 and QMake 3.1 using Qt version 5.11.3

**Comment by guidotack** [comment] 2019-06-06 23:45
Sorry for the late reply. In case you're still interested in getting this to work, you can try the following steps.
After adding the solver configuration in the IDE, can you run minizinc from the command line now? Does Gecode appear in the list of solvers when you run `minizinc --solvers`? Can you compile a model using `minizinc --solver gecode -c model.mzn`? This should result in a file `model.fzn`.

**Comment by a1880** [comment] 2019-06-29 17:52
I am facing the same "Could not determine model parameters" after updating the IDE to 2.3.0 under Windows 7. This happens for all solvers. I uninstalled the IDE and re-installed, but this has not helped.
From within the IDE, I cannot solve any MiniZinc models.

**Comment by Dekker1** [comment] 2019-07-02 01:51
Hi @a1880 ,

We've noticed that when MiniZinc produces a warning it can clutter the JSON output that the IDE requires to determine how to run the model instance. The next version of the IDE will have a better error message, but in the meantime you can run `minizinc --solvers` on the command line. We suspect that this will produce a warning or a error. Resolving the mentioned issue should allow the IDE to work again.

**Comment by a1880** [comment] 2019-07-05 16:26
Bedankt!

I tried as advised and actually got an error/warning as suspected:

C:\Program Files\MiniZinc>minizinc --solvers
Warning: multiple executables 'C:/AK/Programme/or-tools_flatzinc_VisualStudio2017-64bit_v6.4.4495/bin/fzn-or-tools.exe' found on the system, using 'C:\AK\Programme\or-tools_flatzinc_VisualStudio2017-64bit_v6.4.4495\bin\fzn-or-tools.exe'

Not sure, why fzn-or-tools.exe was sought and found there. I removed the path and the problem is gone.

Thanks for your hint!

Axel

**Closed** 2019-12-18 07:16 UTC
