### ISSUE TITLE
desktop file and icons aren't installed

### ISSUE THREAD

**Issue by yurivict** [MiniZinc/MiniZincIDE#142] opened 2021-05-02 20:21 UTC
Version 2.5.5

Please see how the Arch port installs the desktop file and icons: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=minizinc-ide

This is expected to be done by the build itself.

**Comment by Dekker1** [comment] 2021-05-02 22:31
Duplicate of #138

**Closed by Dekker1** 2021-05-02 22:31 UTC
